#!/bin/bash
# add 
# # */10 * * * * * /etc/modbus4mqtt/autorunpro to your crontab (every 10 sec)
# every config.yaml in directory will be launched as own instance of the service 
# for singlerun transmission
# adjust path to your destination
cd /etc/modbus4mqtt/pro/
for f in  $( ls *.yaml); do
         systemctl start modbus4mqttpro@$f.service
        echo $f
done
