#!/bin/bash
#add this with "@reboot" to your crontab
#every config.yaml in directory will be launched as own instance
# adjust path to your destination
sleep 10
cd /etc/modbus4mqtt/
for f in  $( ls *.yaml); do
         systemctl start modbus4mqtt@$f.service
        echo $f
done
