#!/bin/bash
# add 
# # */5 * * * * /etc/modbus4mqtt/autorunconfig to your crontab (every 5 min)
# every config.yaml in directory will be launched as own instance of the service 
# for singlerun transmission
# adjust path to your destination
cd /etc/modbus4mqtt/config/
for f in  $( ls *.yaml); do
         systemctl start modbus4mqtt@$f.service
        echo $f
done
